//
//  HomePresenter.swift
//  AcronymsApp
//
//  Created by Luis Tejada on 5/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomePresenter {

    // MARK: - Private properties -

    private let operationQueue: DispatchQueue = {
        let queue = DispatchQueue(label: "apiQueue", qos: .userInteractive)
        return queue
    }()
    private unowned let view: HomeViewProtocol
    private let interactor: HomeInteractorProtocol
    private let wireframe: HomeWireframeProtocol

    // MARK: - Lifecycle -

    init(
        view: HomeViewProtocol,
        interactor: HomeInteractorProtocol,
        wireframe: HomeWireframeProtocol
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension HomePresenter: HomePresenterProtocol {
    func didLoad() {
        view.reload(data: [Acronyms]())
    }
    
    func search(acronyms: String) {
        operationQueue.async {
            self.view.startActivity()
            self.interactor.request(acronyms: acronyms)
        }
    }
    
    func didReceived(data: [Acronyms]) {
        view.reload(data: data)
        self.view.stopActivity()
    }
    
    func didReceived(error: Error) {
        self.view.presentError(message: error.localizedDescription)
    }
    
}
